[tool.poetry]
name = "line-fitter"
version = "0.1.0"
description = "Line fitter"
authors = ["Your Name <you@example.com>"]

[tool.poetry.dependencies]
python = "^3.7"
lmfit = "^1.0.0"
matplotlib = "^3.2.1"
astropy = "^4.0.1"
colorama = "^0.4.3"
numpy = "^1.18.2"
click = "^7.1.1"

[tool.poetry.dev-dependencies]
mypy = "^0.770"
black = "^19.10b0"
PyYAML = "^5.3.1"
ipython = "^7.13.0"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
